### ISSUE TITLE
Multihost Lilybot for global network reliability tracking

### ISSUE THREAD

**Issue by Zorlin** [Lilypad-Tech/lilybot#1]
We need to make Lilybot multi-host and home it on at least three hosts.

The chosen hosts are:

Hosts:
- [x] Bee, a host in the UK
- [x] Puppycat, a host in the UK
- [x] Vaxis, a host in Australia

We need to do the following tasks to complete this:
- [x] Modify the script to terminate a job forcefully if it takes more than 20 minutes. (This will hopefully stop the bots getting stuck)
- [x] Create a systemd job that starts Lilybot on startup
- [x] Create loggers for each system in BetterStack Logs
- [x] Create private keys for each Lilybot and record their public addresses in 1Password so that we can refill them as needed
- [x] Fill each Lilybot from the faucet

We would like to expand the Lilybot project to also cover Cowsay jobs later, but this is OOS for this task:
- [ ] Add cowsay jobs
- [ ] Add cowsay jobs to the Status page.

**Comment by Zorlin** [comment]
This is done
